### ISSUE TITLE
modeling.m_vgg

### ISSUE THREAD

**Issue by Chrisz7709** [rongliangzi/MARUNet#9]
Hello, when attempting to run "python train_generic.py --model MARNet --epochs 100 --dataset qnrf --train_json json/qnrf_train.json --val_json json/qnrf_val.json --loss 3avg-ms-ssim --lazy_val 0" I get the error code "Traceback (most recent call last):
  File "train_generic.py", line 26, in <module>
    from modeling import *
  File "C:\Users\Horton\MARUNet\modeling\__init__.py", line 3, in <module>
    from .m_vgg import M_VGG
ModuleNotFoundError: No module named 'modeling.m_vgg' "
Would I be able to get some clarification if there is supposed to be a file named "modeling.m_vgg"?

**Comment by rongliangzi** [comment]
Hi, you can remove the lines raising errors and only keep line 1, 24, 29.
These lines appear there because I used them to compare different modules earlier, and you can find those module in history commits.
Hope it helps.
